Integer variables: Used to store whole numbers (positive, negative, or zero)
Example: x = 5

Float variables: Used to store decimal numbers
Example: y = 3.14

String variables: Used to store a sequence of characters
Example: name = "John"

Boolean variables: Used to store True or False values
Example: is_raining = True

List variables: Used to store a collection of values (which can be of different data types)
Example: fruits = ["apple", "banana", "orange"]

Tuple variables: Similar to lists, but are immutable (cannot be changed once created)
Example: coordinates = (3, 4)

Set variables: Used to store a collection of unique values (duplicates are automatically removed)
Example: unique_numbers = {1, 2, 3}

Dictionary variables: Used to store a collection of key-value pairs
Example: person = {"name": "John", "age": 25}

a dataframe is a variable in Python. Specifically, a dataframe is a type of object in the pandas library that is used to represent tabular data in a way that is similar to a spreadsheet or a SQL table.

When you create a dataframe in Python using the pandas library, you are essentially creating a new object that is stored in memory and can be referenced using a variable name.



```
# import pandas as pd

data = {'name': ['John', 'Jane', 'Bob'], 'age': [25, 30, 35], 'city': ['New York', 'San Francisco', 'Chicago']}
df = pd.DataFrame(data)

```



In [38]:
import numpy as np
import sys

*Numpy is a multidimensional arrays *

Numpy vs lists :

Numpy is much faster than lists / Cache utilization / Numpy has every feature of list and a lot more / It is a Matlab replacement / Pandas library uses numpy
/ used for machine learning


# **Basics**

In [39]:
a = np.array([1,2,3] , dtype = 'int32')  # 1D
print(a)

[1 2 3]


In [40]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])  #2D
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [41]:
#How to get the dimension
b.ndim

2

In [42]:
#How to get the shape
b.shape

(2, 3)

In [43]:
#get type
b.dtype

dtype('float64')

# Accessing/Changing specific elements

In [44]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [45]:
c.shape

(2, 7)

In [46]:
#Numpy has zero indexing meaning the first index in the row and column is zero
#to see number 13 : second row => index =1 / 6th column => index =6
#c[row,column]

c[1,5]

#you can also use negetaive notation

c[1,-2]

13

In [47]:
#get a row
c[0,:]
#get a column
c[:,2]


array([ 3, 10])

In [48]:
#[start index:end index:stepsize]

c[0,1:6:2]

array([2, 4, 6])

In [49]:
#changing an element

c[1,5] = 20
print(c)
#in a column
c[:,2] = 5
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [50]:
#what if the matrix is in 3d
#GET A SPECIFIC ELEMENT FROM OUTSIDE TO INSIDE

d = np.array([[1,2],[3,4],[5,6]])  #this is 2d !
print(d)
print('\n')
d.shape


e = np.array([[[1,2],[3,4],[5,6],[7,8]]])  #this is 3d
print('\n')
print(e)
e.shape
print('\n')

e[0,1,1]

[[1 2]
 [3 4]
 [5 6]]




[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]




4

# Different Types of Array

In [51]:
#making all zeros
f = np.zeros((2,3),dtype = 'int32')
print(f)

[[0 0 0]
 [0 0 0]]


In [52]:
#all ones
g = np.ones((3,3) , dtype = 'float64')
print(g)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [53]:
#any other array
h = np.full((5,5) , 85)
print(h)

[[85 85 85 85 85]
 [85 85 85 85 85]
 [85 85 85 85 85]
 [85 85 85 85 85]
 [85 85 85 85 85]]


In [54]:
#making a array with the same size
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)
print('\n')
i = np.full_like(c,11)
print(i)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


[[11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11]]


In [55]:
#random numbers
np.random.rand(4,2)

#random integer numbers
np.random.randint(10 , size = (3,3))

#indetity matrix
np.identity(5)  #always a square matrix

#you can add arrays together
number1 = np.full((5,5),10)
number2 = np.full((5,5),-23)
ans  = number1 + number2
print (ans)

[[-13 -13 -13 -13 -13]
 [-13 -13 -13 -13 -13]
 [-13 -13 -13 -13 -13]
 [-13 -13 -13 -13 -13]
 [-13 -13 -13 -13 -13]]


**Be Careful when copying arrays**

when yoy copy and array, whatever change you do to the copy , the same happens for the original one

In [56]:
a =np.array([[1,2],[3,4]])
b = a
b[0,0] = 99
print(b)
print('\n')
print(a)  #changes to b also happened to a
#here is the solution

c  = a.copy()
c[0,0] = 123
print('\n')
print(a)
print('\n')
print(c) #changes were applied only to c

[[99  2]
 [ 3  4]]


[[99  2]
 [ 3  4]]


[[99  2]
 [ 3  4]]


[[123   2]
 [  3   4]]


# Mathematical Operations

In [57]:
#you can do the same things you do with variables  #implemented on all elements
j = np.array([1,2,3,4])
j-2
j+2
j*2
j/2

k = np.array([4,3,2,1])
l = j+k
print(l)

[5 5 5 5]


In [58]:
m = np.array([[1,2],[3,4]])
m ** 2

#finding cosine of all the elemts
np.cos(m)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [59]:
#things are no longer element based
a = np.ones((2,3))
b = np.full((3,2),2)

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [60]:

a = np.array([[1,2],[3,4]])

np.linalg.det(a)

-2.0000000000000004

# Statistics

In [61]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)
np.min(stats)
np.max(stats)
np.max(stats, axis = 1)
np.sum(stats)

[[1 2 3]
 [4 5 6]]


21